package com.jorypestorious.projecteuler;

public class Euler002 {
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    
    public static void main(String[] args) {
        
        int previous1 = 1;
        int previous2 = 2;
        long sum = 2;
        
        for (int i = 3; i < 4000000; i=previous1+previous2) {
            if (i%2==0) sum+=i;
            if (previous1>previous2) previous2 = i;
            else previous1 = i;
        }
        
        System.out.println(sum); // 4613732
    }

}
